# 1. Create a logger
# Define two loggers in this case i.e default root and a custom loggers named sampleLogger
[loggers]
keys=root, sampleLogger

# 2. Create and configure Handlers
#    2(a) create handlers(destination)
[handlers]
keys=consoleHandler
#    2(b) create and configure a formatter for the handlers
[formatters]
keys=sampleFormatter

[formatter_sampleFormatter] # create formatter string
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=%d-%b-%y %H:%M:%S

#   2(c) Configure the handlers with the formatter and any of the default severity level as per project requirements
#       Severity level can be overridden when linking handlers and logger.
[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=sampleFormatter
args=(sys.stdout,)

# 3. Link loggers to handlers
[logger_root]  # configure
level=DEBUG
handlers=consoleHandler

[logger_sampleLogger]
level=DEBUG
handlers=consoleHandler
qualname=sampleLogger
propagate=0