({'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'authz.urls' from 'D:\\OneDrive\\programming\\Projects_Plus\\djangoprojects\\my_projects\\
project3_blog\\authz\\urls.py'> (authz:authz) 'authz/'>], [<URLResolver <module 'django.contrib.auth.urls' from 'C:\\Users\\pilot\\.virtualenvs\\project3_blog-6chuRmEV\\Lib\\site-pac
kages\\django\\contrib\\auth\\urls.py'> (None:None) 'authz/'>], [<URLResolver <module 'blogsite.urls' from 'D:\\OneDrive\\programming\\Projects_Plus\\djangoprojects\\my_projects\\pro
ject3_blog\\blogsite\\urls.py'> (None:None) ''>, <URLPattern '' [name='home']>], [<URLResolver <module 'blogsite.urls' from 'D:\\OneDrive\\programming\\Projects_Plus\\djangoprojects\
\my_projects\\project3_blog\\blogsite\\urls.py'> (None:None) ''>, <URLPattern 'more_articles/' [name='more_articles']>], [<URLResolver <module 'blogsite.urls' from 'D:\\OneDrive\\pro
gramming\\Projects_Plus\\djangoprojects\\my_projects\\project3_blog\\blogsite\\urls.py'> (None:None) ''>, <URLPattern 'article/<int:pk>' [name='article_detail']>], [<URLResolver <mod
ule 'blogsite.urls' from 'D:\\OneDrive\\programming\\Projects_Plus\\djangoprojects\\my_projects\\project3_blog\\blogsite\\urls.py'> (None:None) ''>, <URLPattern 'article/new' [name='
new_article']>], [<URLResolver <module 'blogsite.urls' from 'D:\\OneDrive\\programming\\Projects_Plus\\djangoprojects\\my_projects\\project3_blog\\blogsite\\urls.py'> (None:None) ''>
, <URLPattern 'article/new/success' [name='new_success']>], [<URLResolver <module 'blogsite.urls' from 'D:\\OneDrive\\programming\\Projects_Plus\\djangoprojects\\my_projects\\project
3_blog\\blogsite\\urls.py'> (None:None) ''>, <URLPattern 'article/edit/<int:pk>' [name='article_edit']>], [<URLResolver <module 'blogsite.urls' from 'D:\\OneDrive\\programming\\Proje
cts_Plus\\djangoprojects\\my_projects\\project3_blog\\blogsite\\urls.py'> (None:None) ''>, <URLPattern 'article/edit/success' [name='edit_success']>], [<URLResolver <module 'blogsite.urls' from 'D:\\OneDrive\\programming\\Projects_Plus\\djangoprojects\\my_projects\\project3_blog\\blogsite\\urls.py'> (None:None) ''>, <URLPattern 'article/delete/<int:pk>' [name='article_delete']>], [<URLResolver <module 'blogsite.urls' from 'D:\\OneDrive\\programming\\Projects_Plus\\djangoprojects\\my_projects\\project3_blog\\blogsite\\urls.py'> (None:None) ''>, <URLPattern 'like/<int:pk>' [name='like_post']>], [<URLResolver <module 'blogsite.urls' from 'D:\\OneDrive\\programming\\Projects_Plus\\djangoprojects\\my_projects\\project3_blog\\blogsite\\urls.py'> (None:None) ''>, <URLPattern 'author_profile/<int:id>' [name='author_profile']>], [<URLPattern 'trigger-error500/'>]], 'path': '1'},)